#!/bin/bash
#
# BugZapper - a simple debugger for bash. Usage: bugzapper [target script]
#
# Driver script: Concatenates the preamble (bugzapper.pre) and the target script
# (_guineapig) and then executes the new script making calls to the functions
# contained in bugzapper.fns. All three script files are required to work.
#
# This script is based on a project from "Learning the bash shell", Third
# Edition, by Cameron Newham and Bill Rosenblatt, copyright 2005 O'Reilly
# Media, Inc. 0-596-00965-8.
#
# This program is free software: You can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Original author: Hoyt Harness.
# Send bug reports and any other correspondence to hoyt.harness@gmail.com.
#
# OVERALL TODO:
# - Setting breakpoints is not working correctly.
# - Displaying the test script is not working correctly.

echo 'BugZapper v.0.0.1'

_dbname=${0##*/}

if (( $# < 1 )) ; then
    echo "$_dbname: Usage: $_dbname [filename]" >&2
    exit 1
fi

_guineapig=$1

if [ ! -r $1 ]; then
    echo "$_dbname: Cannot read file '$_guineapig'." >&2
    exit 1
fi

shift

_tmpdir=/tmp
_libdir=.
_debugfile=$_tmpdir/bugzapper.$$  #Temporary file for cat'd script
cat $_libdir/bugzapper.pre $_guineapig > $_debugfile
exec bash $_debugfile $_guineapig $_tmpdir $_libdir "$@"
