#!/bin/bash
#
# BugZapper - a bash debugger (GPLv2)
# Driver script: Concatenates the preamble (bashdb.pre) and the target script
# (_guineapig) and then executes the new script.

echo 'BugZapper v.0.0.0'

_dbname=${0##*/}

if (( $# < 1 )) ; then
    echo "$_dbname: Usage: $_dbname [filename]" >&2
    exit 1
fi

_guineapig=$1

if [ ! -r $1 ]; then
    echo "$_dbname: Cannot read file '$_guineapig'." >&2
    exit 1
fi

shift

_tmpdir=/tmp
_libdir=.
_debugfile=$_tmpdir/bugzapper.$$  #Temporary file for cat'd script
cat $_libdir/bugzapper.pre $_guineapig > $_debugfile
exec bash $_debugfile $_guineapig $_tmpdir $_libdir "$@"
